services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: caddy
    environment:
      SERVER_NAME: dpham.one
    ports:
      - 8080:80
      - 8443:443
      - 8443:443/udp
    volumes:
      - /volume1/docker/wordpress-caddy/caddy/caddy_data:/data
      - /volume1/docker/wordpress-caddy/caddy/caddy_config:/config
      - /volume1/docker/wordpress-caddy/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /volume1/docker/wordpress-caddy/wordpress/html:/var/www/html

  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - /volume1/docker/wordpress-caddy/wordpress/html:/var/www/html
      - /volume1/docker/wordpress-caddy/wordpress/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      WORDPRESS_DB_USER: siteuser
      WORDPRESS_DB_PASSWORD: sitepassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db
      WORDPRESS_CONFIG_EXTRA: define('WP_REDIS_HOST','redis');
      WORDPRESS_ADMIN_USER: dpham
      WORDPRESS_ADMIN_PASSWORD: Bimat-1512
      WORDPRESS_ADMIN_EMAIL: duong15121989@gmail.com
      WORDPRESS_TITLE: 'Duong Pham'
      WORDPRESS_PERMALINK_STRUCTURE: /%postname%/
      WORDPRESS_THEME_TO_INSTALL: "kadence"
      WORDPRESS_PLUGINS_TO_INSTALL: "redis-cache cache-enabler seo-by-rank-math"

  db:
    image: mariadb:10.11.6-jammy
    restart: always
    volumes:
      - /volume1/docker/wordpress/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: siteuser
      MYSQL_PASSWORD: sitepassword
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MARIADB_RANDOM_ROOT_PASSWORD: 1

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    entrypoint: wp
    command: "--info"
    volumes:
      - /volume1/docker/wordpress/html:/var/www/html
